databaseChangeLog:
  - changeSet:
      id: 1767965138235-1
      author: Mr.Arc-T
      changes:
        - createTable:
            tableName: attribute_values
            remarks: Stores possible attribute values
            columns:
              - column:
                  name: id
                  type: ${id.type}
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: attribute_id
                  type: ${integer_value.type}
                  constraints:
                    nullable: false
                    foreignKeyName: fk_attribute_values_attribute
                    references: attributes(id)
                    deleteCascade: true

              - column:
                  name: attribute_value
                  type: ${name.type}
                  constraints:
                    nullable: false
                    unique: true
                  remarks: Supports Persian values

              - column:
                  name: created_at
                  type: ${timestamp_value.type}
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false

        - createIndex:
            tableName: attribute_values
            indexName: idx_attribute_values_attribute
            columns:
              - column:
                  name: attribute_id

        - createIndex:
            tableName: attribute_values
            indexName: idx_attribute_values_value
            columns:
              - column:
                  name: attribute_value

        - createIndex:
            unique: true
            tableName: attribute_values
            indexName: idx_attribute_values_unique
            columns:
              - column:
                  name: attribute_id
              - column:
                  name: attribute_value