databaseChangeLog:
  - changeSet:
      id: 1767965225839-1
      author: Mr.Arc-T
      changes:
        - createTable:
            tableName: product_media
            remarks: Stores product images/videos
            columns:
              - column:
                  name: id
                  type: ${id.type}
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: product_id
                  type: ${integer_value.type}
                  constraints:
                    nullable: false
                    foreignKeyName: fk_media_product
                    references: products(id)

              - column:
                  name: media_type_id
                  type: ${integer_value.type}
                  constraints:
                    nullable: false
                    foreignKeyName: fk_media_type
                    references: media_types(id)

              - column:
                  name: url
                  type: ${short_text.type}
                  constraints:
                    nullable: false
                  remarks: URL to media file

              - column:
                  name: name
                  type: ${short_text.type}
                  constraints:
                    nullable: false
                  remarks: name of the file

              - column:
                  name: display_order
                  type: ${integer_value.type}
                  remarks: 'starts with 1 which is main image for product'
                  constraints:
                    nullable: false

              - column:
                  name: extension
                  type: ${short_text.type}
                  constraints:
                    nullable: false

              - column:
                  name: created_at
                  type: ${timestamp_value.type}
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false

        - createIndex:
            tableName: product_media
            indexName: idx_media_product
            columns:
              - column:
                  name: product_id

        - createIndex:
            tableName: product_media
            indexName: idx_media_type
            columns:
              - column:
                  name: media_type_id