databaseChangeLog:
  - changeSet:
      id: 1767965201746-1
      author: Mr.Arc-T
      changes:
        - createTable:
            tableName: product_reviews
            remarks: Stores product reviews and comments
            columns:
              - column:
                  name: id
                  type: ${id.type}
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: product_id
                  type: ${integer_value.type}
                  constraints:
                    nullable: false
                    foreignKeyName: fk_reviews_product
                    references: products(id)

              - column:
                  name: user_id
                  type: ${integer_value.type}
                  constraints:
                    nullable: false
                    foreignKeyName: fk_reviews_user
                    references: users(id)

              - column:
                  name: action_type
                  type: VARCHAR(500)
                  #                  type: ENUM('LIKE', 'COMMENT', 'SHARE', 'COMPARE', 'QUESTION', 'SAVED')
                  constraints:
                    nullable: false

              - column:
                  name: action_details
                  type: ${long_text.type}
                  constraints:
                    nullable: false
                  remarks: Supports Persian comments

              - column:
                  name: created_at
                  type: ${timestamp_value.type}
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false

              - column:
                  name: updated_at
                  type: ${timestamp_value.type}
                  constraints:
                    nullable: true

              - column:
                  name: deleted_at
                  type: ${timestamp_value.type}
                  constraints:
                    nullable: true

        - createIndex:
            tableName: product_reviews
            indexName: idx_product_reviews_product
            columns:
              - column:
                  name: product_id

        - createIndex:
            tableName: product_reviews
            indexName: idx_product_reviews_user
            columns:
              - column:
                  name: user_id

        - createIndex:
            unique: true
            tableName: product_reviews
            indexName: idx_product_reviews_unique
            columns:
              - column:
                  name: user_id
              - column:
                  name: product_id
