databaseChangeLog:
  - changeSet:
      id: 1783792605596-5
      author: Mr.Arc-T
      changes:
        - createTable:
            schemaName: catalog
            tableName: products
            remarks: Stores product-specific information for catalog items
            columns:
              - column:
                  name: id
                  type: ${id.type}
                  constraints:
                    nullable: false

              - column:
                  name: description
                  type: ${long_text.type}
                  constraints:
                    nullable: true

        - addPrimaryKey:
            schemaName: catalog
            tableName: products
            columnNames: id
            constraintName: pk_products

        - addForeignKeyConstraint:
            baseTableSchemaName: catalog
            baseTableName: products
            baseColumnNames: id
            referencedTableSchemaName: catalog
            referencedTableName: items
            referencedColumnNames: id
            constraintName: fk_products_item