databaseChangeLog:
  - changeSet:
      id: 1768464192730-1
      author: Mr.Arc-T
      changes:
        - insert:
            schemaName: catalog
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
                  valueNumeric: '1'
              - column:
                  name: attribute_id
                  valueNumeric: '1'
              - column:
                  name: attribute_value_id
                  valueNumeric: '2'

        - insert:
            schemaName: catalog
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
                  valueNumeric: '1'
              - column:
                  name: attribute_id
                  valueNumeric: '1'
              - column:
                  name: attribute_value_id
                  valueNumeric: '3'

        - insert:
            schemaName: catalog
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
                  valueNumeric: '2'
              - column:
                  name: attribute_id
                  valueNumeric: '2'
              - column:
                  name: attribute_value_id
                  valueNumeric: '4'

        - insert:
            schemaName: catalog
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
                  valueNumeric: '2'
              - column:
                  name: attribute_id
                  valueNumeric: '2'
              - column:
                  name: attribute_value_id
                  valueNumeric: '5'

        - insert:
            schemaName: catalog
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
                  valueNumeric: '4'
              - column:
                  name: attribute_id
                  valueNumeric: '2'
              - column:
                  name: attribute_value_id
                  valueNumeric: '6'

        - insert:
            schemaName: catalog
            tableName: product_attribute_values
            columns:
              - column:
                  name: product_id
                  valueNumeric: '4'
              - column:
                  name: attribute_id
                  valueNumeric: '2'
              - column:
                  name: attribute_value_id
                  valueNumeric: '7'